### ISSUE TITLE
Gui Texture gizmo should be controlled by its Ui elements rect transform.

### ISSUE THREAD

**Issue by FrayedFunction** [MccDev260/com.mccdev260.gizmo-tool#12]
At the moment its controlled by its own rect transform which is annoying to work with. In v1.2.0 I want to add a toggle to allow it to be controlled by the UI elements rect transform instead.

**Comment by MccDev260** [comment]
Will consider this again if I find I need it or someone else creates an issue. Removed origin option from inspector for this type.

**Comment by FrayedFunction** [comment]
Will consider this again if I find I need it or someone else creates an issue. Removed origin option from inspector for this type.
