### ISSUE TITLE
Add Option to use Origin Transform values (Mesh&WireMesh)

### ISSUE THREAD

**Issue by FrayedFunction** [MccDev260/com.mccdev260.gizmo-tool#5]
If for whatever reason theres a need to use values from a completely different object, add a bool that toggles the option to copy the transform values from the object set in Origin Transform.

**Comment by FrayedFunction** [comment]
Need to add this as mesh types are functionally useless without it

**Comment by MccDev260** [comment]
Never mind, I'm an idiot and I've already done it lol
